### PR TITLE
DateTime class

### PR DESCRIPTION
**Pull request by MarieKP95**
Fixed some issues in the DateTime class, implemented class method _combine()_ and instance method _replace()_. Made tests.

### CODE REVIEW

**Comment by carlenlund** [comment]
You've done a really good job! One question before I can give any feedback, how exactly do I run your tests?

It seems like the `org.python` package is missing from the classpath?

image

**Comment by TomoYang** [comment]
Is this right that some test cases cannot pass
image

**Comment by MarieKP95** [comment]
> You've done a really good job! One question before I can give any feedback, how exactly do I run your tests?
> 
> It seems like the `org.python` package is missing from the classpath?
> 
> image

We ran the tests on IntelliJ. First _ant java_ in the terminal then Run -> Run 'test_datetime' or Run 'test_datetime' with Coverage. Did not write any commands to run the tests, only through IntelliJ.

We did not get that problem with org.python, what did the error say?

**Comment by TomoYang** [comment]
> minal then Run -> Run 'test_datetime' or Run 'test_datetime' with Coverage. Did not write any commands to run the tests, only through IntelliJ.
> 
> We did not get that problem with org.python, what did the error say?

I have solved this problem with compiling the python-support-java. Thanks you

**Comment by MarieKP95** [comment]
> Is this right that some test cases cannot pass
> image

All tests should pass. What does it say for those that did not pass?
tests

**Comment by TomoYang** [comment]
> > Is this right that some test cases cannot pass
> > image
> 
> All tests should pass. What does it say for those that did not pass?
> tests

image

**Comment by carlenlund** [comment]
All tests seem to pass now. I made a small commit to fix error in a test for exceptions.
We will do a proper code review soon!

**Review by TomoYang — CHANGES_REQUESTED** [review]
code has not duplicated; 
the code is in the right directory;
the code following the coding conventions for VOC;
the function and names follow the name of the original python;
the codes seem maintainable;
pass all test cases;
good coverage test but not 100% lines;

todo:
run `ant checkstyle` command passes for all new code.
format code in `DateTime.java` according to checkstyle

**Comment by MarieKP95** [comment]
> code has not duplicated;
> the code is in the right directory;
> the code following the coding conventions for VOC;
> the function and names follow the name of the original python;
> the codes seem maintainable;
> pass all test cases;
> good coverage test but not 100% lines;
> 
> todo:
> run `ant checkstyle` command passes for all new code.
> format code in `DateTime.java` according to checkstyle

Fixed the errors now for DateTime, except for one that says that the file needs to end with a new line. I'm using Windows and its "new line" is not the correct one.

**Review by carlenlund — APPROVED** [review]
Looks good to me!
Now only @Karroda needs to approve the PR

**Pull request merged**
