### PR TITLE
Sprint2 oscar tsegay

### PR DESCRIPTION
**Pull request by ralfkatt**

### CODE REVIEW

**Review by CarolinaGripsborn — COMMENTED** [review]
No duplication of code.
Code is located in the correct files and directories.
Coding conventions seems to be followed.
Code appears maintainable, follows the single responsibility principle.
All tests pass.
Tests coverage is good for methods (90%), slightly less for lines (66%).

TODOS
- [ ] Function names for the comparison methods are not the same as in the python doc and other classes (__eq__, __ge__, __gt__, __le__, __lt__, __neq__), also missing the neq function.
- [ ] Some style errors when running "ant checkstyle"

**Review by MarieKP95 — CHANGES_REQUESTED** [review]
It should be named __xx__ where xx is eq, neq, le, lt, ge and gt. Have you done `ant checkstyle` and fixed the errors for Date.java file?

**Comment by MarieKP95** [comment]
> It should be named __xx__ where xx is eq, neq, le, lt, ge and gt. Have you done `ant checkstyle` and fixed the errors for Date.java file?

It seems like the underscores around xx is not showing up on the comment. It should be `__xx__` with 2 underscores on each side.

**Review by MarieKP95 — APPROVED** [review]
Method names are good now. Tests also covers 90% of methods and 70% of lines. No more checkstyle errors for Date.java file. Looks good!

**Pull request merged**
