### PR TITLE
math.factorial()

### PR DESCRIPTION
**Pull request by MarieKP95**
Added new math module file where factorial function has been implemented. Also added a new test file test_math.py that tests the factorial function.

### CODE REVIEW

**Review by CarolinaGripsborn — COMMENTED** [review]
- No duplicated code
- [ ]  The function implementation should be put in python/common/python instead of python/common/org/python
- The code seems to adhere to the VOC conventions including the function declaration and correct testing format
- The function name is good, very descriptive
- The code looks maintainable, the function follows the single-responsibility principle 
- The added tests are passing
- [ ] The coverage can be improved, currently only positive integers are being tested. Could add incorrect inputs such as a negative number

**Review by TomoYang — DISMISSED** [review]
Modify the code according to our comments. Now, it looks fine.

But the import location should be changed from package org.python; to package python; Otherwise, I don't think it can be run

**Review by TomoYang — COMMENTED** [review]
Modify the code according to our comments. Now, it looks fine.

But the import location should be changed from package org.python; to package python; Otherwise, I don't think it can be run. We can discuss tomorrow, I think

**Comment by MarieKP95** [comment]
> Modify the code according to our comments. Now, it looks fine.
> 
> But the import location should be changed from package org.python; to package python; Otherwise, I don't think it can be run. We can discuss tomorrow, I think

Aah thank you! The tests runs now without the AssertionError for me when I changed to package python.

**Review by TomoYang — APPROVED** [review]

**Pull request merged**
